name: Server CI Template
on:
  workflow_call:

jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: check secret
        run: echo MODIFIED
      - name: check secret
        run: echo ${{secrets.MY_TEST_SECRET}}
      - name: check secret 2
        run: if [ "${{secrets.MY_TEST_SECRET}}" = "test123" ]; then echo ok; else echo not ok; fi
      - name: check files
        run: cat README.md
