name: Server CI PR

on:
  pull_request:
  
jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display PR Info
        run: |
          echo "This is my code now"
