name: test1

on:
  workflow_run:
    workflows:
      - "Server CI PR"
    types:
      - completed

jobs:
  log_info:
    runs-on: ubuntu-latest
    steps:
    - name: log
      run: |
        echo "${{github.repository_owner}}"; echo "${{github.event.workflow_run.event}}";