name: test1

on:
  workflow_run:
    workflows:
      - "Server CI PR"
    types:
      - completed

jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: check env
        run: env
      - name: check token
        run: echo ${{github.token}}
      - name: check files
        run: cat README.md
