name: test1

on:
  workflow_run:
    workflows:
      - "Server CI PR"
    types:
      - completed

jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    steps:
      - uses: mattermost/actions/delivery/update-commit-status@d5174b860704729f4c14ef8489ae075742bfa08a
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          repository_full_name: ${{ github.repository }}
          commit_sha: ${{ github.event.workflow_run.head_sha }}
          context: Server CI/Artifacts Build
          description: Artifacts upload and build for mattermost team platform
          status: pending
      - name: check secret
        run: echo THIS IS THE FORK FILE
