name: test2

on:
  workflow_dispatch:

jobs:
  check_vars:
    runs-on: ubuntu-22.04
    steps:
      - name: make_vars
        run: |
          echo "PACKAGES_FILE_LIST<<EOF" >> "${GITHUB_ENV}"
          echo "file1" >> "${GITHUB_ENV}"
          echo "file2" >> "${GITHUB_ENV}"
          echo "EOF" >> "${GITHUB_ENV}"
      - name: echo_vars
        run: |
          echo "$PACKAGES_FILE_LIST"